## data

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_label_complete = pd.read_csv("TRAVEL_APP_label_complete.csv")

In [3]:
df_label_complete

_id     app_name  user_score   user_date  \
0      662f099973f7ce16925e6b4f  tripadvisor           2  2019-12-16   
1      662f099a73f7ce16925e6b50  tripadvisor           1  2020-03-20   
2      662f099a73f7ce16925e6b58  tripadvisor           2  2019-08-05   
3      662f099a73f7ce16925e6b5c  tripadvisor           1  2019-04-09   
4      662f099b73f7ce16925e6b69  tripadvisor           2  2019-01-12   
...                         ...          ...         ...         ...   
16623  662f3b7534754d6a96872ba7   skyscanner           3  2019-07-23   
16624  662f3b7534754d6a96872bac   skyscanner           3  2019-07-20   
16625  662f3b7534754d6a96872bc7   skyscanner           3  2019-06-14   
16626  662f3b7634754d6a96872bf6   skyscanner           3  2019-05-07   
16627  662f3b7634754d6a96872bf8   skyscanner           3  2019-05-06   

                                           user_comments  \
0      웹사이트에서 구글로 로긴하고 예약한다음 메일에 티켓 다운로드하기가 있길래 폰에서 앱...   
1      최근 업데이트후 실시간 항공권 가격이 낚시성 가격으로 나오고 결제는 실제로 되지 않...   
2      리뷰를 썼는데 보내기 버튼을 누르면 곧 사라진것처럼 보이며 빈칸이니 글을 작성하라는...   
3      수정된 버전 너무 좋아서 잘쓰고 있다가 왜 또...wtf 새로운 기능 부탁하는것도 ...   
4        조언은 들을수 있지만. 해당 음식점의 메뉴라던지 가격대라던지의 정보가 없어서 별로에요   
...                                                  ...   
16623  예약하려는 티켓의 클래스와 마일리지 적립율, 마일리지 등의 정보가 상세정보에 같이 ...   
16624                                                 보통   
16625  어플을 삭제해도 계속 지워지지 않다가 반복하다보니 어플은 배경화면에서 삭제되었는데 ...   
16626  국내선 검색하니까 에어부산은 있길래 저가항공 다 나올줄알고 매번 검색해도 항상 에어...   
16627  카카오톡으로 공유하기가 안됨\n최신버전의 앱 아니라고만 나옴 \n스카이스캐너가 업데...   

                                       review_preprocess  \
0      웹사이트에서 구글로 로긴하고 예약한다음 메일에 티켓 다운로드하기가 있길래 폰에서 앱...   
1      최근 업데이트후 실시간 항공권 가격이 낚시성 가격으로 나오고 결제는 실제로 되지 않...   
2      리뷰를 썼는데 보내기 버튼을 누르면 곧 사라진것처럼 보이며 빈칸이니 글을 작성하라는...   
3      수정된 버전 너무 좋아서 잘쓰고 있다가 왜 또...wtf 새로운 기능 부탁하는것도 ...   
4        조언은 들을수 있지만. 해당 음식점의 메뉴라던지 가격대라던지의 정보가 없어서 별로에요   
...                                                  ...   
16623  예약하려는 티켓의 클래스와 마일리지 적립율, 마일리지 등의 정보가 상세정보에 같이 ...   
16624                                                 보통   
16625  어플을 삭제해도 계속 지워지지 않다가 반복하다보니 어플은 배경화면에서 삭제되었는데 ...   
16626  국내선 검색하니까 에어부산은 있길래 저가항공 다 나올줄알고 매번 검색해도 항상 에어...   
16627  카카오톡으로 공유하기가 안됨\n최신버전의 앱 아니라고만 나옴 \n스카이스캐너가 업데...   

                                      review_clean_mecab  \
0      웹 사이트 구글 로 예약 다음 메일 티켓 다운로드 있 폰 앱 다운로드 같 구글 계정...   
1      최근 업데이트 후 실시간 항공 가격 낚시 가격 나오 결제 되 경우 많 실망 최저 업...   
2                      리뷰 보내 버튼 누르 보이 칸 글 작성 메세지 반복 사용 앱   
3      수정 버전 좋 쓰 기능 부탁 호텔 모텔 비앤비 특수 숙박 종합 순위 전 유지 하 그...   
4                              조언 들 있 해당 음식점 메뉴 가격대 정보 없   
...                                                  ...   
16623               예약 티켓 클래스 마일리지 적립 마일리지 정보 상세 정보 표시 좋   
16624                                                 보통   
16625            플 삭제 반복 플 배경 화면 삭제 앱 스토어 들어오 열기 열리 플 작동   
16626  국내선 검색  있 저 항공 알 검색  없 표 없 알 값 표 예매 앱 자체 제주 이스...   
16627                          카카오톡 공유 됨 최신 버전 앱  업데이트 되   

                                        review_clean_okt  label  
0      웹사이트 구글 로 기다 예약 한 다음 메일 티켓 다운로드  있다 폰 앱 다운로드  ...      0  
1      최근 업데이트 후 실시간 항공권 가격 낚시 가격 나오다 결제 실제  않다 경우 많아...      0  
2      리뷰 써다 보내다 버튼 누르다 곧 사라지다 보이 빈칸 글 작성 메세지 반복  사용 ...      0  
3      수정  버전 좋다 잘쓰다 있다 왜 또 새롭다 기능 부탁  아니다 호텔 모텔 비앤비 ...      0  
4                 조언 들다 있다 해당 음식점 메뉴 던지다 가격 던지다 정보 없다 별로      0  
...                                                  ...    ...  
16623      예약  티켓 클래스 마일리지 적립 율 마일리지 등 정보 상세 정보 표시  좋다 함      1  
16624                                                 보통      1  
16625  어플 삭제  계속 지워지다 않다 반복   어플 배경화면 삭제 되어다 앱스토어 들어오...      0  
16626  국내선 검색  있다 저가 항공 나오다 알 매번 검색  항상  없다 표 없다 알 비싸...      0  
16627                 카카오톡 공유  안 최신 버전 앱 아니다 나오다  업데이트 안      0  

[16628 rows x 9 columns]

In [ ]:
# pd.set_option('display.max_rows', None)  # 모든 행을 출력하도록 설정합니다.

## mecab 명사만 추출

In [4]:
!pip install python-mecab-ko

In [5]:
from mecab import MeCab
mecab = MeCab()

In [11]:
mecab.pos(df_label_complete['review_clean_okt'][5])

[('프로필', 'NNG'),
 ('변경', 'NNG'),
 ('안', 'MAG'),
 ('계속', 'MAG'),
 ('리셋', 'NNG'),
 ('식당', 'NNG'),
 ('예약', 'NNG'),
 ('메일', 'NNG'),
 ('받', 'VV'),
 ('다', 'EC'),
 ('예약', 'NNG'),
 ('리스트', 'NNG'),
 ('없', 'VA'),
 ('다', 'EF'),
 ('어', 'IC'),
 ('쩌', 'MAG'),
 ('건지', 'VV'),
 ('다', 'EC'),
 ('모르', 'VV'),
 ('다', 'EC')]

In [12]:
def mecab_tag(text):
    morphs_nouns = []
    morphs_nouns_list = []
    for sentence in text:
        # 명사, 형용사, 동사
        morphs = [morph for morph, tag in mecab.pos(sentence) if tag in ['NNG']]
        morphs_nouns.append(' '.join(morphs))
    
    return morphs_nouns

In [14]:
morphs_nouns = mecab_tag(df_label_complete['review_clean_okt'])

In [15]:
df_label_complete['review_clean_noun'] = morphs_nouns

In [16]:
df_label_complete['review_clean_noun']

0        웹 사이트 구글 기다 예약 다음 티켓 다운로드 폰 앱 다운로드 구글 계정 로그인 예...
1        최근 업데이트 후 실시간 항공 가격 낚시 가격 결제 실제 경우 실망 최저 업체 클릭...
2                                 버튼 보이 칸 글 작성 메세지 반복 사용 앱
3             수정 버전 기능 부탁 호텔 모텔 특수 숙박 종합 순위 유지 기능 경우 별점 수정
4                                       조언 해당 음식점 메뉴 가격 정보
                               ...                        
16623                       예약 티켓 마일리지 적립 마일리지 정보 상세 정보 표시
16624                                                   보통
16625                        플 삭제 반복 플 배경 화면 삭제 앱 스토어 플 작동
16626               국내선 검색 항공 알 검색 표 값 표 예매 앱 자체 스타 항공사 낭비
16627                                     안 최신 버전 앱 업데이트 안
Name: review_clean_noun, Length: 16628, dtype: object

## topic 분류

In [17]:
df_label_complete

_id     app_name  user_score   user_date  \
0      662f099973f7ce16925e6b4f  tripadvisor           2  2019-12-16   
1      662f099a73f7ce16925e6b50  tripadvisor           1  2020-03-20   
2      662f099a73f7ce16925e6b58  tripadvisor           2  2019-08-05   
3      662f099a73f7ce16925e6b5c  tripadvisor           1  2019-04-09   
4      662f099b73f7ce16925e6b69  tripadvisor           2  2019-01-12   
...                         ...          ...         ...         ...   
16623  662f3b7534754d6a96872ba7   skyscanner           3  2019-07-23   
16624  662f3b7534754d6a96872bac   skyscanner           3  2019-07-20   
16625  662f3b7534754d6a96872bc7   skyscanner           3  2019-06-14   
16626  662f3b7634754d6a96872bf6   skyscanner           3  2019-05-07   
16627  662f3b7634754d6a96872bf8   skyscanner           3  2019-05-06   

                                           user_comments  \
0      웹사이트에서 구글로 로긴하고 예약한다음 메일에 티켓 다운로드하기가 있길래 폰에서 앱...   
1      최근 업데이트후 실시간 항공권 가격이 낚시성 가격으로 나오고 결제는 실제로 되지 않...   
2      리뷰를 썼는데 보내기 버튼을 누르면 곧 사라진것처럼 보이며 빈칸이니 글을 작성하라는...   
3      수정된 버전 너무 좋아서 잘쓰고 있다가 왜 또...wtf 새로운 기능 부탁하는것도 ...   
4        조언은 들을수 있지만. 해당 음식점의 메뉴라던지 가격대라던지의 정보가 없어서 별로에요   
...                                                  ...   
16623  예약하려는 티켓의 클래스와 마일리지 적립율, 마일리지 등의 정보가 상세정보에 같이 ...   
16624                                                 보통   
16625  어플을 삭제해도 계속 지워지지 않다가 반복하다보니 어플은 배경화면에서 삭제되었는데 ...   
16626  국내선 검색하니까 에어부산은 있길래 저가항공 다 나올줄알고 매번 검색해도 항상 에어...   
16627  카카오톡으로 공유하기가 안됨\n최신버전의 앱 아니라고만 나옴 \n스카이스캐너가 업데...   

                                       review_preprocess  \
0      웹사이트에서 구글로 로긴하고 예약한다음 메일에 티켓 다운로드하기가 있길래 폰에서 앱...   
1      최근 업데이트후 실시간 항공권 가격이 낚시성 가격으로 나오고 결제는 실제로 되지 않...   
2      리뷰를 썼는데 보내기 버튼을 누르면 곧 사라진것처럼 보이며 빈칸이니 글을 작성하라는...   
3      수정된 버전 너무 좋아서 잘쓰고 있다가 왜 또...wtf 새로운 기능 부탁하는것도 ...   
4        조언은 들을수 있지만. 해당 음식점의 메뉴라던지 가격대라던지의 정보가 없어서 별로에요   
...                                                  ...   
16623  예약하려는 티켓의 클래스와 마일리지 적립율, 마일리지 등의 정보가 상세정보에 같이 ...   
16624                                                 보통   
16625  어플을 삭제해도 계속 지워지지 않다가 반복하다보니 어플은 배경화면에서 삭제되었는데 ...   
16626  국내선 검색하니까 에어부산은 있길래 저가항공 다 나올줄알고 매번 검색해도 항상 에어...   
16627  카카오톡으로 공유하기가 안됨\n최신버전의 앱 아니라고만 나옴 \n스카이스캐너가 업데...   

                                      review_clean_mecab  \
0      웹 사이트 구글 로 예약 다음 메일 티켓 다운로드 있 폰 앱 다운로드 같 구글 계정...   
1      최근 업데이트 후 실시간 항공 가격 낚시 가격 나오 결제 되 경우 많 실망 최저 업...   
2                      리뷰 보내 버튼 누르 보이 칸 글 작성 메세지 반복 사용 앱   
3      수정 버전 좋 쓰 기능 부탁 호텔 모텔 비앤비 특수 숙박 종합 순위 전 유지 하 그...   
4                              조언 들 있 해당 음식점 메뉴 가격대 정보 없   
...                                                  ...   
16623               예약 티켓 클래스 마일리지 적립 마일리지 정보 상세 정보 표시 좋   
16624                                                 보통   
16625            플 삭제 반복 플 배경 화면 삭제 앱 스토어 들어오 열기 열리 플 작동   
16626  국내선 검색  있 저 항공 알 검색  없 표 없 알 값 표 예매 앱 자체 제주 이스...   
16627                          카카오톡 공유 됨 최신 버전 앱  업데이트 되   

                                        review_clean_okt  label  \
0      웹사이트 구글 로 기다 예약 한 다음 메일 티켓 다운로드  있다 폰 앱 다운로드  ...      0   
1      최근 업데이트 후 실시간 항공권 가격 낚시 가격 나오다 결제 실제  않다 경우 많아...      0   
2      리뷰 써다 보내다 버튼 누르다 곧 사라지다 보이 빈칸 글 작성 메세지 반복  사용 ...      0   
3      수정  버전 좋다 잘쓰다 있다 왜 또 새롭다 기능 부탁  아니다 호텔 모텔 비앤비 ...      0   
4                 조언 들다 있다 해당 음식점 메뉴 던지다 가격 던지다 정보 없다 별로      0   
...                                                  ...    ...   
16623      예약  티켓 클래스 마일리지 적립 율 마일리지 등 정보 상세 정보 표시  좋다 함      1   
16624                                                 보통      1   
16625  어플 삭제  계속 지워지다 않다 반복   어플 배경화면 삭제 되어다 앱스토어 들어오...      0   
16626  국내선 검색  있다 저가 항공 나오다 알 매번 검색  항상  없다 표 없다 알 비싸...      0   
16627                 카카오톡 공유  안 최신 버전 앱 아니다 나오다  업데이트 안      0   

                                       review_clean_noun  
0      웹 사이트 구글 기다 예약 다음 티켓 다운로드 폰 앱 다운로드 구글 계정 로그인 예...  
1      최근 업데이트 후 실시간 항공 가격 낚시 가격 결제 실제 경우 실망 최저 업체 클릭...  
2                 

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

### 부정

In [19]:
# 텍스트 데이터 전처리 및 벡터화
vectorizer = TfidfVectorizer()
feature_negative = vectorizer.fit_transform(df_label_complete.query('label == 0')['review_clean_noun'])

In [20]:
# LDA 모델 훈련
lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(feature_negative)

LatentDirichletAllocation(n_components=5, random_state=42)

In [21]:
# 훈련된 LDA 모델로 문서별 토픽 할당
document_topics = lda.transform(feature_negative)

# 각 문서의 주요 토픽 확인
for idx, topic in enumerate(document_topics):
    print(f"Document {idx} belongs to Topic {topic.argmax()}")

Document 0 belongs to Topic 0
Document 1 belongs to Topic 1
Document 2 belongs to Topic 1
Document 3 belongs to Topic 2
Document 4 belongs to Topic 0
Document 5 belongs to Topic 0
Document 6 belongs to Topic 0
Document 7 belongs to Topic 1
Document 8 belongs to Topic 0
Document 9 belongs to Topic 1
Document 10 belongs to Topic 2
Document 11 belongs to Topic 4
Document 12 belongs to Topic 0
Document 13 belongs to Topic 1
Document 14 belongs to Topic 0
Document 15 belongs to Topic 1
Document 16 belongs to Topic 0
Document 17 belongs to Topic 4
Document 18 belongs to Topic 1
Document 19 belongs to Topic 4
Document 20 belongs to Topic 1
Document 21 belongs to Topic 1
Document 22 belongs to Topic 1
Document 23 belongs to Topic 3
Document 24 belongs to Topic 2
Document 25 belongs to Topic 3
Document 26 belongs to Topic 4
Document 27 belongs to Topic 1
Document 28 belongs to Topic 0
Document 29 belongs to Topic 4
Document 30 belongs to Topic 4
Document 31 belongs to Topic 0
Document 32 belong

In [22]:
# 토픽 모델링 결과 해석
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(lda.components_):
    # 토픽별로 상위 단어 10개 출력
    top_word_indices = topic.argsort()[:-10-1:-1]
    top_words = [feature_names[i] for i in top_word_indices if i < len(feature_names)]
    print(f"Topic {topic_idx}: {', '.join(top_words)}")

Topic 0: 예약, 취소, 사용, 전화, 고객, 짜증, 센터, 환불, 연락, 연결
Topic 1: 검색, 결제, 항공, 항공권, 예약, 가격, 환불, 수수료, 취소, 시간
Topic 2: 삭제, 업데이트, 가격, 검색, 쓰레기, 표시, 사이트, 별점, 강제, 지도
Topic 3: 업데이트, 불편, 검색, 다운로드, 가격, 설치, 구간, 안보, 수정, 관광지
Topic 4: 로그인, 가입, 오류, 회원, 쿠폰, 실행, 정보, 사용, 자동, 확인


### 긍정

In [23]:
# 텍스트 데이터 전처리 및 벡터화
vectorizer = TfidfVectorizer()
feature_negative = vectorizer.fit_transform(df_label_complete.query('label == 1')['review_clean_noun'])

In [24]:
# LDA 모델 훈련
lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(feature_negative)

LatentDirichletAllocation(n_components=5, random_state=42)

In [25]:
# 훈련된 LDA 모델로 문서별 토픽 할당
document_topics = lda.transform(feature_negative)

# 각 문서의 주요 토픽 확인
for idx, topic in enumerate(document_topics):
    print(f"Document {idx} belongs to Topic {topic.argmax()}")

Document 0 belongs to Topic 2
Document 1 belongs to Topic 4
Document 2 belongs to Topic 2
Document 3 belongs to Topic 3
Document 4 belongs to Topic 2
Document 5 belongs to Topic 4
Document 6 belongs to Topic 4
Document 7 belongs to Topic 1
Document 8 belongs to Topic 2
Document 9 belongs to Topic 1
Document 10 belongs to Topic 2
Document 11 belongs to Topic 1
Document 12 belongs to Topic 4
Document 13 belongs to Topic 2
Document 14 belongs to Topic 2
Document 15 belongs to Topic 4
Document 16 belongs to Topic 1
Document 17 belongs to Topic 0
Document 18 belongs to Topic 2
Document 19 belongs to Topic 2
Document 20 belongs to Topic 2
Document 21 belongs to Topic 4
Document 22 belongs to Topic 2
Document 23 belongs to Topic 3
Document 24 belongs to Topic 4
Document 25 belongs to Topic 3
Document 26 belongs to Topic 2
Document 27 belongs to Topic 2
Document 28 belongs to Topic 4
Document 29 belongs to Topic 1
Document 30 belongs to Topic 4
Document 31 belongs to Topic 4
Document 32 belong

In [26]:
# 토픽 모델링 결과 해석
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(lda.components_):
    # 토픽별로 상위 단어 10개 출력
    top_word_indices = topic.argsort()[:-10-1:-1]
    top_words = [feature_names[i] for i in top_word_indices if i < len(feature_names)]
    print(f"Topic {topic_idx}: {', '.join(top_words)}")

Topic 0: 이용, 편리, 유이, 예약, 여행, 사용, 상품, 티켓, 구매, 쓸다
Topic 1: 가격, 비교, 최저, 항공, 사이트, 검색, 비행기, 가성, 한눈, 세계
Topic 2: 정보, 사용, 필요, 여행, 투어, 추천, 다양, 가이드, 여행지, 현지
Topic 3: 여행, 최고, 도움, 필수, 감사, 준비, 자유, 계획, 해외여행, 해외
Topic 4: 일정, 여행, 만족, 검색, 기능, 맛집, 지도, 동선, 장소, 계획


### 분석

[부정]
- Topic 0: 예약, 취소, 사용, 전화, 고객, 짜증, 센터, 환불, 연락, 연결
- Topic 1: 검색, 결제, 항공, 항공권, 예약, 가격, 환불, 수수료, 취소, 시간
- Topic 2: 삭제, 업데이트, 가격, 검색, 쓰레기, 표시, 사이트, 별점, 강제, 지도
- Topic 3: 업데이트, 불편, 검색, 다운로드, 가격, 설치, 구간, 안보, 수정, 관광지
- Topic 4: 로그인, 가입, 오류, 회원, 쿠폰, 실행, 정보, 사용, 자동, 확인

[긍정]
- Topic 0: 이용, 편리, 유이, 예약, 여행, 사용, 상품, 티켓, 구매, 쓸다
- Topic 1: 가격, 비교, 최저, 항공, 사이트, 검색, 비행기, 가성, 한눈, 세계
- Topic 2: 정보, 사용, 필요, 여행, 투어, 추천, 다양, 가이드, 여행지, 현지
- Topic 3: 여행, 최고, 도움, 필수, 감사, 준비, 자유, 계획, 해외여행, 해외
- Topic 4: 일정, 여행, 만족, 검색, 기능, 맛집, 지도, 동선, 장소, 계획

[부정]
- Topic 0: 고객센터 연결 관련
- Topic 1: 항공권 예약 환불 수수료 관련
- Topic 2: 앱 사용 후기(별점) 강제 관련
- Topic 3: 업데이트 후 불편 관련
- Topic 4: 로그인, 가입, 쿠폰 사용 오류 관련

[긍정]
- Topic 0: 이용 편리하다.
- Topic 1: 가격 비교하기 좋다. 한눈에 볼 수 있다.
- Topic 2: 투어 정보가 다양하다?
- Topic 3: 여행 시 필수앱이다.
- Topic 4: 일정, 동선 기능이 만족스럽다.

## 앱별로 긍, 부정 나누기

In [40]:
tripadvisor = df_label_complete.query("app_name == 'tripadvisor'")
triple = df_label_complete.query("app_name == 'triple'")
myrealtrip = df_label_complete.query("app_name == 'myrealtrip'")
skyscanner = df_label_complete.query("app_name == 'skyscanner'")

### 트립어드바이저

#### 부정

In [41]:
df_sheets = []
for sheet_name, df in tripadvisor.query("label == 0")['review_clean_noun'].items() :
  df_sheets.append(df)

In [43]:
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(df_sheets)
features.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.30951595, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.29562585, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [44]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=3, random_state=111) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features)

LatentDirichletAllocation(n_components=3, random_state=111)

In [45]:
dictionary_list = vectorizer.get_feature_names_out()

In [48]:
## 상위 단어 추출 
## 0 확률 1은 dictionary
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:4])# 시리즈 형식으로 출력 get values from series / index 
    print(topics_text)
    topics_list.append(topics_text)
' '.join(df_topics[1].values[:4]) #시리즈를 하나에 문장 생성
topics_list_add = [['Topic0', 'Topic1', 'Topic2'],topics_list]
df_topics_keywords = pd.DataFrame(topics_list_add)
df_topics_keywords.T

오류 자동 예약 제거
삭제 짜증 사용 설치
업데이트 검색 불편 사진


0              1
0  Topic0    오류 자동 예약 제거
1  Topic1    삭제 짜증 사용 설치
2  Topic2  업데이트 검색 불편 사진

In [ ]:
topics_output = lda_model.transform(features)

In [ ]:
df_topics_score = pd.DataFrame(topics_output)

In [ ]:
df_topics_score['dominant_topic_number']=np.argmax(topics_output, axis=1)

In [ ]:
df_topics_score['sentences']=df_sheets

In [ ]:
df_topics_score.query("dominant_topic_number == 0")

#### 긍정

In [65]:
df_sheets = []
for sheet_name, df in tripadvisor.query("label == 1")['review_clean_noun'].items() :
  df_sheets.append(df)

In [66]:
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(df_sheets)
features.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [67]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=3, random_state=111) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features)

LatentDirichletAllocation(n_components=3, random_state=111)

In [69]:
dictionary_list = vectorizer.get_feature_names_out()

In [70]:
## 상위 단어 추출 
## 0 확률 1은 dictionary
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:4])# 시리즈 형식으로 출력 get values from series / index 
    print(topics_text)
    topics_list.append(topics_text)
' '.join(df_topics[1].values[:4]) #시리즈를 하나에 문장 생성
topics_list_add = [['Topic0', 'Topic1', 'Topic2'],topics_list]
df_topics_keywords = pd.DataFrame(topics_list_add)
df_topics_keywords.T

최고 이용 사용 유이
편리 필요 감사 비교
정보 여행 도움 필수


0            1
0  Topic0  최고 이용 사용 유이
1  Topic1  편리 필요 감사 비교
2  Topic2  정보 여행 도움 필수

### 트리플

#### 부정

In [49]:
df_sheets = []
for sheet_name, df in triple.query("label == 0")['review_clean_noun'].items() :
  df_sheets.append(df)

In [50]:
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(df_sheets)
features.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [51]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=3, random_state=111) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features)

LatentDirichletAllocation(n_components=3, random_state=111)

In [52]:
dictionary_list = vectorizer.get_feature_names_out()

In [53]:
## 상위 단어 추출 
## 0 확률 1은 dictionary
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:4])# 시리즈 형식으로 출력 get values from series / index 
    print(topics_text)
    topics_list.append(topics_text)
' '.join(df_topics[1].values[:4]) #시리즈를 하나에 문장 생성
topics_list_add = [['Topic0', 'Topic1', 'Topic2'],topics_list]
df_topics_keywords = pd.DataFrame(topics_list_add)
df_topics_keywords.T

예약 처리 결제 취소
일정 여행 도시 검색
예약 수수료 취소 수정


0             1
0  Topic0   예약 처리 결제 취소
1  Topic1   일정 여행 도시 검색
2  Topic2  예약 수수료 취소 수정

#### 긍정

In [71]:
df_sheets = []
for sheet_name, df in triple.query("label == 1")['review_clean_noun'].items() :
  df_sheets.append(df)

In [72]:
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(df_sheets)
features.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [73]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=3, random_state=111) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features)

LatentDirichletAllocation(n_components=3, random_state=111)

In [74]:
dictionary_list = vectorizer.get_feature_names_out()

In [75]:
## 상위 단어 추출 
## 0 확률 1은 dictionary
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:4])# 시리즈 형식으로 출력 get values from series / index 
    print(topics_text)
    topics_list.append(topics_text)
' '.join(df_topics[1].values[:4]) #시리즈를 하나에 문장 생성
topics_list_add = [['Topic0', 'Topic1', 'Topic2'],topics_list]
df_topics_keywords = pd.DataFrame(topics_list_add)
df_topics_keywords.T

도움 여행 도시 저장
최고 여행 일정 친구
여행 일정 정보 계획


0            1
0  Topic0  도움 여행 도시 저장
1  Topic1  최고 여행 일정 친구
2  Topic2  여행 일정 정보 계획

### 마이리얼트립

#### 부정

In [54]:
df_sheets = []
for sheet_name, df in myrealtrip.query("label == 0")['review_clean_noun'].items() :
  df_sheets.append(df)

In [55]:
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(df_sheets)
features.toarray()

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.1293655, 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]])

In [56]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=3, random_state=111) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features)

LatentDirichletAllocation(n_components=3, random_state=111)

In [57]:
dictionary_list = vectorizer.get_feature_names_out()

In [58]:
## 상위 단어 추출 
## 0 확률 1은 dictionary
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:4])# 시리즈 형식으로 출력 get values from series / index 
    print(topics_text)
    topics_list.append(topics_text)
' '.join(df_topics[1].values[:4]) #시리즈를 하나에 문장 생성
topics_list_add = [['Topic0', 'Topic1', 'Topic2'],topics_list]
df_topics_keywords = pd.DataFrame(topics_list_add)
df_topics_keywords.T

취소 환불 예약 결제
로그인 가입 업데이트 회원
쿠폰 오류 탈퇴 최악


0               1
0  Topic0     취소 환불 예약 결제
1  Topic1  로그인 가입 업데이트 회원
2  Topic2     쿠폰 오류 탈퇴 최악

#### 긍정

In [76]:
df_sheets = []
for sheet_name, df in myrealtrip.query("label == 1")['review_clean_noun'].items() :
  df_sheets.append(df)

In [77]:
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(df_sheets)
features.toarray()

array([[0.        , 0.        , 0.16547591, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [78]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=3, random_state=111) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features)

LatentDirichletAllocation(n_components=3, random_state=111)

In [79]:
dictionary_list = vectorizer.get_feature_names_out()

In [80]:
## 상위 단어 추출 
## 0 확률 1은 dictionary
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:4])# 시리즈 형식으로 출력 get values from series / index 
    print(topics_text)
    topics_list.append(topics_text)
' '.join(df_topics[1].values[:4]) #시리즈를 하나에 문장 생성
topics_list_add = [['Topic0', 'Topic1', 'Topic2'],topics_list]
df_topics_keywords = pd.DataFrame(topics_list_add)
df_topics_keywords.T

티켓 구매 해외여행 할인
여행 편리 사용 필수
이용 투어 예약 최고


0              1
0  Topic0  티켓 구매 해외여행 할인
1  Topic1    여행 편리 사용 필수
2  Topic2    이용 투어 예약 최고

### 스카이스캐너

#### 부정

In [59]:
df_sheets = []
for sheet_name, df in skyscanner.query("label == 0")['review_clean_noun'].items() :
  df_sheets.append(df)

In [60]:
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(df_sheets)
features.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.10966428, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [61]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=3, random_state=111) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features)

LatentDirichletAllocation(n_components=3, random_state=111)

In [62]:
dictionary_list = vectorizer.get_feature_names_out()

In [63]:
## 상위 단어 추출 
## 0 확률 1은 dictionary
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:4])# 시리즈 형식으로 출력 get values from series / index 
    print(topics_text)
    topics_list.append(topics_text)
' '.join(df_topics[1].values[:4]) #시리즈를 하나에 문장 생성
topics_list_add = [['Topic0', 'Topic1', 'Topic2'],topics_list]
df_topics_keywords = pd.DataFrame(topics_list_add)
df_topics_keywords.T

검색 가격 결제 불편
업데이트 금액 사용 항공사
시간 검색 설정 가격


0               1
0  Topic0     검색 가격 결제 불편
1  Topic1  업데이트 금액 사용 항공사
2  Topic2     시간 검색 설정 가격

#### 긍정

In [81]:
df_sheets = []
for sheet_name, df in skyscanner.query("label == 1")['review_clean_noun'].items() :
  df_sheets.append(df)

In [82]:
vectorizer = TfidfVectorizer()
features = vectorizer.fit_transform(df_sheets)
features.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [83]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=3, random_state=111) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features)

LatentDirichletAllocation(n_components=3, random_state=111)

In [84]:
dictionary_list = vectorizer.get_feature_names_out()

In [85]:
## 상위 단어 추출 
## 0 확률 1은 dictionary
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:4])# 시리즈 형식으로 출력 get values from series / index 
    print(topics_text)
    topics_list.append(topics_text)
' '.join(df_topics[1].values[:4]) #시리즈를 하나에 문장 생성
topics_list_add = [['Topic0', 'Topic1', 'Topic2'],topics_list]
df_topics_keywords = pd.DataFrame(topics_list_add)
df_topics_keywords.T

검색 항공권 정보 항공
최고 가격 비교 최저
편리 이용 사용 유이


0             1
0  Topic0  검색 항공권 정보 항공
1  Topic1   최고 가격 비교 최저
2  Topic2   편리 이용 사용 유이

### 분석

[트립어드바이저]
|topic|부정|분석|topic|긍정|분석|
|--|--|--|--|--|--|
|Topic0|오류 자동 예약 제거|예약 오류가 잦고 앱 제거가 안됨, 자동(강제) 업데이트 및 설치 됨|Topic0|최고 이용 사용 유이|사용하기 편하다|
|Topic1|삭제 짜증 사용 설치|앱 삭제 안됨, 사용 불편|Topic1|편리 필요 감사 비교|가격 비교시 좋음|
|Topic2|업데이트 검색 불편 사진|업데이트 팝업을 계속 띄움, 검색이 불편하고 부정확함, 사진이 관광지와 다름|Topic2|정보 여행 도움 필수|정보가 많다|

[트리플]
|topic|부정||topic|긍정||
|--|--|--|--|--|--|
|Topic0|예약 처리 결제 취소|예약 취소 불가, 결제 오류 잦음|Topic0|도움 여행 도시 저장|저장 기능이 있다|
|Topic1|일정 여행 도시 검색|일정 짜는 것이 어려움, 도시가 한정적임, 검색 매우 불편|Topic1|최고 여행 일정 친구|일정짜기, 친구와 일정 공유 기능|
|Topic2|예약 수수료 취소 수정|예약 취소 수수료가 비싸다|Topic2|여행 일정 정보 계획|여행 계획 짤 때 좋음|

[마이리얼트립]
|topic|부정||topic|긍정||
|--|--|--|--|--|--|
|Topic0|취소 환불 예약 결제|취소 환불 어려움, 결제 시스템 불편함|Topic0|티켓 구매 해외여행 할인|티켓 저렴하게 구매, 해외여행갈 때 주로 이용, 할인 많다|
|Topic1|로그인 가입 업데이트 회원|로그인 실패, 가입 불편, 가입 유도, 회원가입 에러|Topic1|여행 편리 사용 필수|여행 필수 앱|
|Topic2|쿠폰 오류 탈퇴 최악|쿠폰 발급 오류, 회원 탈퇴 버튼 없음|Topic2|이용 투어 예약 최고|투어 예약 편함|

[스카이스캐너]
|topic|부정||topic|긍정||
|--|--|--|--|--|--|
|Topic0|검색 가격 결제 불편|검색 후 들어가면 가격이 다름|Topic0|검색 항공권 정보 항공|검색 옵션 많음, 정보 알기 쉬움|
|Topic1|업데이트 금액 사용 항공사|업데이트하고 불편해짐, 금액이 다른 경우 많음|Topic1|최고 가격 비교 최저|최저가로 구매 잘함, 가격 비교하기 좋음|
|Topic2|시간 검색 설정 가격|시간 낭비했다|Topic2|편리 이용 사용 유이|사용하기 편리함|

## 결론

[부정]
- 부정 리뷰의 경우 대체로 앱 오류 문제가 많음.
- 사용이 불편하다 -> 사용자 입장에서 알기 쉽도록, 사용 편리하도록 페이지 디자인
- 예약 취소 수수료가 비싸다 -> 타 사이트들 보다 수수료를 낮춘다는 마케팅 가능
- 실 결제시 가격이 달라지는 문제 -> 우리 사이트는 처음 보여지는 가격과 결제시 가격이 같아요!! 라는 마케팅 가능

[긍정]
- 여러가지 상품의 가격을 비교해서 보는 기능
- 자주 이용하는 교통수단이나 자주 가는 지역 등등을 저장하는 기능
- 검색 옵션 많으면 좋다
- 다른 사용자와 일정을 공유하는 기능